# 站点设置
name: mokusei  
description: This is a hexo theme 
favicon: 
banner: /imgs/head.jpg
rss: 

# 是否延用站点配置文件的标题和描述，而不是主题里的设置
useSiteName: true
useSiteDescription: true

# 导航栏
# 菜单项为YAML标识符（例如：homepage, archive, about），
# 需要你自行在多语言配置文件（位于languages子目录）中为各个菜单项添加翻译
#
# ** 特殊菜单项（直接添加字段，无需指定值与url等属性）： **
# - _languageSwitcher, _langSwitcher: 多语言切换器
menu:
  homepage:
    url: /
    icon: home
    iconType: fa
  archives:
    url: /archives/
  about:
    url: none
    child:
        aboutThisWebsite:
          url: /about
  _languageSwitcher:    # 多语言切换器

# 社交图标
account:
  github:
    url: /github
    icon: github
    iconType: fa
  mail:
    url: /mail
    icon: envelope
    iconType: fa
  twitter:
    url: /twitter
    icon: twitter
    iconType: fa

# 以下配置中的1为开启，0为关闭

# 布局
layout:
  columnPosition: 1 #边栏放置位置，默认右边，0为左边
  headSearchIcon: 1 #导航栏是否显示搜索图标

# 边栏小工具
toolbar:
  displaySwitch: 1 #是否显示边栏
  # 边栏各个小工具排列顺序，数字越大排在后面
  position:
    searchWidget: 0
    postWidget: 1
    tagsWidget: 2
    categoriesWidget: 3
  # 边栏各个小工具是否显示开关
  display:
    searchWidget: 0
    postWidget: 1
    tagsWidget: 1
    categoriesWidget: 1

# 文章相关
article:
  dateSwitch: 1 #是否显示文章日期
  categoriesSwitch: 1 #是否显示文章分类
  tagSwitch: 1 #是否显示文章标签

# disqus评论
comment:
  disqus:
    shortname: 

# 粒子特效开关
ifsparticle:  1

# 多语言站点支持
# 这要求你将不同语言独立为不同的站点，每个站点都是public下的二级子目录。默认语言直接使用网站根目录
# 详细的配置过程见文档
#
# 注：在导航栏（上方menu字段）中添加字段_languageSwitcher以显示导航栏
i18n:
  languageList:
    zh-cn:
      name: 简体中文
    en:
      name: English
  default: en
  showSwitcher: true