# site
# 站点设置
name: mokusei
description: This is a hexo theme
favicon:
banner: /imgs/head.jpg
rss:  

# navigation
# 导航
menu:
  主页:
    url: /
    icon: home
    iconType: fa
  归档:
    url: /archives/
  关于:
    url: none
    child:
        关于本站:
          url: /about

# Social account
# 社交图标
account:
  github:
    url: /github
    icon: github
    iconType: fa
  mail:
    url: /mail
    icon: envelope
    iconType: fa
  twitter:
    url: /twitter
    icon: twitter
    iconType: fa

# layout
# 布局
layout:
  columnPosition: 1
  headSearchIcon: 1

# sidebar widget
# 边栏小工具
toolbar:
  displaySwitch: 1
  position:
    searchWidget: 0
    postWidget: 1
    tagsWidget: 2
    categoriesWidget: 3
  display:
    searchWidget: 0
    postWidget: 1
    tagsWidget: 1
    categoriesWidget: 1

# article
# 文章相关
article:
  dateSwitch: 1
  categoriesSwitch: 1

# Comment system
# 评论
comment:
  disqus:
    shortname: 

# Features
# 粒子特效开关
ifsparticle:  true