# site
# 站点设置
name: mokusei
description: This is a hexo theme
favicon:
banner: /imgs/head.jpg
rss:  

# navigation
# 导航
menu:
  主页:
    url: /
    icon: home
    iconType: fa
  归档:
    url: /archives/
  关于:
    url: none
    child:
        关于本站:
          url: /about

# Social account
# 社交图标
account:
  github:
    url: /github
    icon: github
    iconType: fa
  mail:
    url: /mail
    icon: envelope
    iconType: fa
  twitter:
    url: /twitter
    icon: twitter
    iconType: fa

# layout
# 布局
layout:
  columnPosition: 1



# Comment system
# 评论
comment:
  disqus:
    shortname: 

# Features
# 粒子特效开关
ifsparticle:  true